[package]
name = "xen"
version = "0.0.0"
edition = "2018"

[dependencies]
xen-sys = { path = "../xen-sys" }
cty = "0.2"
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
log = "0.4"
displaydoc = {version = "0.2", default-features = false }

[build-dependencies]
cc = "1.0"
