[package]
name = "xen-sys"
version = "0.0.0"
edition = "2018"

[dependencies]
cty = "0.2.2"

[build-dependencies]
bindgen = { version = "0.59.2", default-features = false, features = ["runtime", "which-rustfmt"] }
