[target.x86_64-unknown-none]
runner = "./run.sh"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "relocation-model=static"
]

[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
