#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

/**
 * Panics if input == 5 otherwise returns
 */
void panic_if_5(uintptr_t input);

/**
 * Prints a message from Rust
 */
void hello(void);
